# Generated by Django 5.2.4 on 2025-07-12 06:57

import django.db.models.deletion
import subscription.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionModel',
            fields=[
                ('id', models.CharField(default=subscription.models.generate_random_id, max_length=10, primary_key=True, serialize=False)),
                ('package_type', models.CharField(choices=[('One_Time', 'One_Time'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='One_Time', max_length=10)),
                ('package_status', models.CharField(choices=[('Active', 'Active'), ('Postpone', 'Postpone')], default='Postpone', max_length=10)),
                ('package_amount', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Total_revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscriptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(choices=[('One_Time', 'One_Time'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='One_Time', max_length=10)),
                ('is_active', models.BooleanField(default=False)),
                ('package_start_date', models.DateField(blank=True, null=True)),
                ('package_end_date', models.DateField(blank=True, null=True)),
                ('package_amount', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
