# Generated by Django 5.2.4 on 2025-08-20 09:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('User', 'User'), ('AI', 'AI')], max_length=10)),
                ('content', models.TextField()),
                ('flagged', models.BooleanField(default=False)),
                ('flag_type', models.CharField(blank=True, choices=[('Received from Adjuster', 'Received from Adjuster'), ('Sent to Adjuster', 'Sent to Adjuster')], max_length=30, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='Chat.chatsession')),
            ],
        ),
        migrations.CreateModel(
            name='FlaggedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(blank=True, max_length=30, null=True)),
                ('flagged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('flagged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flagged_entry', to='Chat.chatmessage')),
            ],
        ),
        migrations.CreateModel(
            name='UserClaimUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('insurance_company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('policy_number', models.CharField(blank=True, max_length=100, null=True)),
                ('police_report_number', models.CharField(blank=True, max_length=100, null=True)),
                ('adjuster_name', models.CharField(blank=True, max_length=255, null=True)),
                ('adjuster_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('add_claim_number', models.CharField(blank=True, max_length=100, null=True)),
                ('adjuster_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('upload_folder_path', models.CharField(blank=True, max_length=500, null=True)),
                ('files_metadata', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
