# Generated by Django 5.2.4 on 2025-07-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='chat_type',
            field=models.CharField(choices=[('BENGI_AI', 'Bengi AI Assistant'), ('CLAIM_THREAD', 'Claim Thread to Insurer')], max_length=20),
        ),
    ]
