# Generated by Django 5.2.4 on 2025-07-21 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0003_alter_chatsession_options_chatsession_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='chat_type',
        ),
    ]
