# Generated by Django 5.2.4 on 2025-07-25 06:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0004_remove_chat_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserClaimUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('insurance_company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('policy_number', models.CharField(blank=True, max_length=100, null=True)),
                ('police_report_number', models.CharField(blank=True, max_length=100, null=True)),
                ('adjuster_name', models.CharField(blank=True, max_length=255, null=True)),
                ('adjuster_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('add_claim_number', models.CharField(blank=True, max_length=100, null=True)),
                ('adjuster_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('upload_folder_path', models.CharField(blank=True, max_length=500, null=True)),
                ('files_metadata', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
