# Generated by Django 5.2.4 on 2025-07-09 03:27

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_customuser_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsaAndPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_and_conditions', models.TextField()),
                ('privacy_policy', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
