# Generated by Django 5.2.4 on 2025-07-09 06:50

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_customuser_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TermsaAndPolicy',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
