# Generated by Django 5.2.4 on 2025-07-12 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_claim', models.CharField(choices=[('Car Theft', 'Car Theft'), ('Collision (Accident)', 'Collision (Accident)'), ('Injury After Accident', 'Injury After Accident'), ('Vandalism / Damage While Parked', 'Vandalism / Damage While Parked'), ('House Fire', 'House Fire'), ('Basement Flood / Water Damage', 'Basement Flood / Water Damage'), ('Roof Damage / Storm', 'Roof Damage / Storm'), ('Vandalism / Forced Entry', 'Vandalism / Forced Entry'), ('Broken Appliances / Home Systems', 'Broken Appliances / Home Systems'), ('Personal Contents Stolen', 'Personal Contents Stolen'), ('Storage Unit Theft', 'Storage Unit Theft'), ('Garage / Shed Damage', 'Garage / Shed Damage')], max_length=100)),
                ('description', models.TextField()),
                ('date_of_incident', models.DateField()),
                ('country_of_incident', models.CharField(choices=[('United States', 'United States'), ('Canada', 'Canada')], max_length=100)),
                ('city_of_incident', models.CharField(max_length=100)),
                ('insurance_company_name', models.CharField(max_length=255)),
                ('policy_number', models.CharField(max_length=100)),
                ('police_report_number', models.CharField(blank=True, max_length=100, null=True)),
                ('policy_document', models.FileField(blank=True, null=True, upload_to='claims/documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
