# Generated by Django 5.2.4 on 2025-07-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Submission', 'Submission'), ('Follow-Up', 'Follow-Up'), ('Negotiation', 'Negotiation'), ('Closure', 'Closure'), ('Policy', 'Policy')], max_length=50)),
                ('last_updated', models.CharField(max_length=20)),
                ('preview', models.TextField()),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
            ],
        ),
    ]
