# Generated by Django 5.2.4 on 2025-07-21 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0002_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insuranceclaim',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='insuranceclaim',
            name='insurance_company_name',
        ),
        migrations.RemoveField(
            model_name='insuranceclaim',
            name='police_report_number',
        ),
        migrations.RemoveField(
            model_name='insuranceclaim',
            name='policy_document',
        ),
        migrations.RemoveField(
            model_name='insuranceclaim',
            name='policy_number',
        ),
    ]
